services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped

    environment:
      VERSION: "custom"
      USERNAME: "MASTER"
      PASSWORD: "admin@123"

      RAM_SIZE: "12G"
      CPU_CORES: "4"
      DISK_SIZE: "30G"

      ENABLE_KVM: "N"
      ENABLE_TPM: "Y"
      ENABLE_SECURE_BOOT: "N"
      NET_MODE: "nat"

    volumes:
      - ./vmdata:/storage
      - ./isos:/boot/iso

    ports:
      - "8006:8006"
      - "3389:3389"
